server:
  port:9007
spring:
  datasorce:
    name: test
    url:jdbc: mysql://urmyall.xyz:3306/ycjj
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvicitionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements:true
    maxOpenPreparedStatements: 20

  mybatis:
    mapper-location: classpath:mapping/*.xml
    type-aliases-package: com.wyb.model

  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethondsArguments: true
    params: count=countSql
